// Generated by CoffeeScript 1.7.1
(function() {
  var SimpleTextEditor;

  SimpleTextEditor = {
    init: function() {
      var boldBtn, italicBtn;
      this.editbox = document.querySelector('#editbox');
      if (!this.editbox) {
        throw new Error('The editbox element has not been defined');
      }
      this.editbox.addEventListener('keyup', this.saveData, false);
      boldBtn = document.querySelector('#bold');
      if (boldBtn) {
        boldBtn.addEventListener('click', (function(_this) {
          return function(e) {
            return _this.toggleBold(e);
          };
        })(this));
      }
      italicBtn = document.querySelector('#italic');
      if (italicBtn) {
        italicBtn.addEventListener('click', (function(_this) {
          return function(e) {
            return _this.toggleItalic(e);
          };
        })(this));
      }
      return this.restoreDocument();
    },
    saveData: function() {
      var timeout;
      return timeout = window.setTimeout((function(_this) {
        return function() {
          var data;
          window.clearTimeout(timeout);
          data = _this.editbox.innerHTML;
          return window.localStorage.setItem('content', data);
        };
      })(this), 2000);
    },
    restoreDocument: function() {
      if (window.localStorage.content) {
        return this.editbox.innerHTML = window.localStorage.content;
      }
    },
    toggleItalic: function() {
      document.execCommand('italic');
      return this.saveData(null);
    },
    toggleBold: function() {
      document.execCommand('bold');
      return this.saveData(null);
    }
  };

  SimpleTextEditor.init();

}).call(this);
